In [5]:
import numpy as np

a = np.random.randn(5)

In [6]:
print(a)

[ 0.47353834 -1.14832683 -0.14637929  1.80133652  0.01287351]


In [7]:
print(a.shape)

(5,)


In [8]:
print(a.T)

[ 0.47353834 -1.14832683 -0.14637929  1.80133652  0.01287351]


In [9]:
print(np.dot(a,a.T))

4.809298963654344


In [10]:
a = np.random.randn(5,1)
print(a)

[[-0.12618365]
 [-0.54382767]
 [ 0.32022798]
 [ 1.1988338 ]
 [-0.79330837]]


In [11]:
print(a.T)

[[-0.12618365 -0.54382767  0.32022798  1.1988338  -0.79330837]]


In [12]:
print(np.dot(a,a.T))

[[ 0.01592231  0.06862216 -0.04040754 -0.15127323  0.10010255]
 [ 0.06862216  0.29574854 -0.17414884 -0.65195899  0.43142305]
 [-0.04040754 -0.17414884  0.10254596  0.38390013 -0.25403954]
 [-0.15127323 -0.65195899  0.38390013  1.43720247 -0.95104489]
 [ 0.10010255  0.43142305 -0.25403954 -0.95104489  0.62933818]]
